### ISSUE TITLE
rqt can no longer find any plugins

### ISSUE THREAD

**Issue by cubercsl** [ros-noetic-arch/ros-noetic-rqt#1]
Upstream issue. Since Python 3.9 the previously deprecated function getiterator on ElementTree has been removed.

https://github.com/ros-visualization/rqt/pull/241
https://github.com/ros-visualization/rqt/issues/240

**Comment by acxz** [comment]
thx for reporting, feel free to make a PR that uses the upstream patch.

**Comment by acxz** [comment]
Closing as dup of https://github.com/ros-noetic-arch/ros-noetic-rqt-gui/issues/2
